Traceback (most recent call last):
  File "C:\Users\matth\PycharmProjects\ExcelParsers\1.0\main.py", line 1035, in <module>
    main()
  File "C:\Users\matth\PycharmProjects\ExcelParsers\1.0\main.py", line 27, in main
    new_data_flag_raise()
  File "C:\Users\matth\PycharmProjects\ExcelParsers\1.0\main.py", line 87, in new_data_flag_raise
    send_data_to_verification()
  File "C:\Users\matth\PycharmProjects\ExcelParsers\1.0\main.py", line 146, in send_data_to_verification
    fill_df_to_verify(data_to_verification)
  File "C:\Users\matth\PycharmProjects\ExcelParsers\1.0\parsed_data_checker.py", line 66, in fill_df_to_verify
    df_to_verify[column][line] = data[line][verified_data_mask_dict[column]]
KeyError: 'code'
